TR = {}

if Config.Language == "EN" then
TR = {
["noinfo"] = "DELETED",             
["youhavejailed"] = "You have been JAILED, your dossier nr is ",
["adddossier"] = "You have added DOSSIER for ",
["adddossier2"] = " with NR: ",
["you_registered"] = "You have registered an citizen ! ",
["already_register"] = "This person is already registered, or there is an error trying find this person !",
["no_user"] = "This person dosen't exist, make sure the person id is valid !",
["youhavecharged"] = "You received a FINE and charged ",
["already_released"] = "You have been released from penitentiary, your place is not anymore here !",
["spawnin_jail"] = "Seems you must finish a sentence before you are free to go !",
["alreadyhavefood"] = "You already have some food, eat it to have more !",
["alreadyhavedrink"] = "You already have some drinks, drink it to have more !",
["yougetfood"] = "You got something to eat !",
["yougetdrink"] = "You got something to drink !",
["inv_full"] = "You don't have space to carry this",
["jailed_text"] = "JAILED", 
["jailed_textdesc"] = "You are now prisoner of Sisika Penitentiary",  
["not_allowed"] = "You are not allowed to stay so close to this ZONE !", 
["nomoney_bounty"] = "You don't have enought money to add this BOUNTY !",
["error_insert"] = "The FINE or BOUNTY amount are incorrect, please check it!", 
["jailtime"] = "JAILTIME:", 
["days"] = "Days",         
["hours"] = "Hours",  
["minutes"] = "Minutes",   
["seconds"] = "Seconds",
["m"] = "M",    
["f"] = "F",    
--MENU
["canteen"] = "Canteen Foods",
["canteendesc"] = "Foods for inmates",
["takefood"] = "Take Food",
["takefooddesc"] = "Take some food",
["takedrink"] = "Take Drinks",
["takedrinkdesc"] = "Take some drinks",
["you_getregistered"] = "You have been registered with identity of",
["not_jobgrade"] = "You are not authorized to do this",
["dossier_deleted"] = "You deleted the DOSSIER NR:",
        
--ERRORS INPUTS
["error_description"] = "The DESCRIPTION is required!",
["error_fine"] = "The FINE is required, 0 for NO FINE!",
["error_bounty"] = "The BOUNTY is required, 0 for NO BOUNTY!",
["error_charge"] = "The CHARGE is REQUIRED !",
["error_jail"] = "The JAIL is required, 0 for NO JAIL!",
["error_id"] = "The citizen id is REQUIRED !",
["error_days"] = "The DAY should be composed by 2 numbers like 01,05,18...",
["error_month"] = "The MONTH should be composed by 2 numbers like 01,05,12...",
["error_age"] = "The AGE should be composed by 2 numbers like 21,45,35...",
["error_cm"] = "The CM should be composed over 2 numbers like 80,135,140...",
["error_kg"] = "The KG should be composed over 2 numbers like 55,165,35...",
["error_eyes"] = "The EYES should be composed over 2 letters like blue,black...",
["error_hair"] = "The HAIR should be composed over 2 letters like black,blonde...",
        
["jail_startjob"] = "You started to job for this Country, you will receive an sentence reduce every crop. Go outside on the farm field to start working !",
["sentence_reduced1"] = "Your sentence has been reduced by ",
["sentence_reduced2"] = " seconds !",
["sentence_reduced3"] = " seconds, And got $",

["tooclose_lastjob"] = "You already worked here, go find another place to break the weeds",
["seizure_property"] = "You have seizure this property! And cannot be accesed by nobody !",
["unseizure_property"] = "You have un-seizure this property! And now can be used by everybody", 
["dossier_notfound"] = "The dossier dosen't exist, or you type it wrong !",
["progressbar_working"] = "Working for reducing of sentence...",
["not_anymoreon"] = "This player is not anymore online",
["dossier_desc"] = "DOSSIER: ",
}
elseif Config.Language == "DE" then
TR = {
["noinfo"] = "GELÖSCHT",
["added_dossier"] = "Sie haben eine AKTE hinzugefügt für ",
["youhavejailed"] = "Sie wurden ins Gefängnis gebracht, Ihre Aktennummer lautet ",
["adddossier"] = "Sie haben eine AKTE hinzugefügt für ",
["adddossier2"] = " mit NR: ",
["you_registered"] = "Sie haben einen Bürger registriert!",
["already_register"] = "Diese Person ist bereits registriert!",
["no_user"] = "Diese Person existiert nicht, stellen Sie sicher, dass die Person ID gültig ist!",
["youhavecharged"] = "Sie haben eine Geldstrafe erhalten und müssen bezahlen ",
["already_released"] = "Sie wurden aus dem Gefängnis entlassen, Ihr Platz ist nicht mehr hier!",
["spawnin_jail"] = "Sie müssen scheinbar eine Strafe verbüßen, bevor Sie freigelassen werden können!",
["alreadyhavefood"] = "Sie haben bereits Essen, essen Sie es, um mehr zu bekommen!",
["alreadyhavedrink"] = "Sie haben bereits Getränke, trinken Sie sie, um mehr zu bekommen!",
["yougetfood"] = "Sie haben etwas zu essen bekommen!",
["yougetdrink"] = "Sie haben etwas zu trinken bekommen!",
["inv_full"] = "Sie haben keinen Platz, um dies zu tragen",
["jailed_text"] = "INHAFTIERT",
["jailed_textdesc"] = "Sie sind nun Gefangener des Alcatrz-Penitentiary",
["not_allowed"] = "Sie dürfen sich nicht so nah an dieser ZONE aufhalten!",
["nomoney_bounty"] = "Sie haben nicht genug Geld, um diese BEUTE hinzuzufügen!",
["error_insert"] = "Der STRAFE- oder BEUTE-Betrag ist inkorrekt, bitte überprüfen Sie es!",
["jailtime"] = "INHAFTIERUNGSZEIT:",
["days"] = "Tage",
["hours"] = "Stunden",
["minutes"] = "Minuten",
["seconds"] = "Sekunden",
["m"] = "M",
["f"] = "F",
--MENU
["canteen"] = "Kantinenessen",
["canteendesc"] = "Essen für Insassen",
["takefood"] = "Essen nehmen",
["takefooddesc"] = "Nimm etwas zu essen",
["takedrink"] = "Getränke nehmen",
["takedrinkdesc"] = "Nimm etwas zu trinken",
["you_getregistered"] = "Deine Identiät wurde registriert ",
["not_jobgrade"] = "Du bist nicht berechtigt, dies zu tun",
["dossier_deleted"] = "Du hast die AKTEN-NR. gelöscht:",
        
["error_description"] = "Die BESCHREIBUNG ist erforderlich!",
["error_fine"] = "Die STRAFE ist erforderlich, 0 für KEINE STRAFE!",
["error_bounty"] = "Die BELOHNUNG ist erforderlich, 0 für KEINE BELOHNUNG!",
["error_charge"] = "Die GEBÜHR ist ERFORDERLICH!",
["error_jail"] = "Das GEFÄNGNIS ist erforderlich, 0 für KEIN GEFÄNGNIS!",
["error_id"] = "Die Bürger ID ist ERFORDERLICH!",
["error_days"] = "Der TAG muss aus 2 Zahlen wie 01, 05, 18 bestehen...",
["error_month"] = "Der MONAT muss aus 2 Zahlen wie 01, 05, 12 bestehen...",
["error_age"] = "Das ALTER sollte aus 2 Zahlen wie 21, 45, 35 bestehen...",
["error_cm"] = "Die KÖRPERGRÖßE sollte aus 2 Zahlen wie 80, 135, 140 bestehen...",
["error_kg"] = "Das GEWICHT sollte aus 2 Zahlen wie 55, 165, 35 bestehen...",
["error_eyes"] = "Die AUGEN sollten aus 2 Buchstaben wie blau, schwarz usw. bestehen...",
["error_hair"] = "DAS HAAR sollte aus 2 Buchstaben wie schwarz, blond usw. bestehen...",

["jail_startjob"] = "Du hast den Job für dieses Land begonnen. Deine Strafe wird bei jeder Ernte reduziert. Gehe nach draußen auf das Feld, um mit der Arbeit zu beginnen!",
["sentence_reduced1"] = "Deine Strafe wurde um ",
["sentence_reduced2"] = " Sekunden reduziert!",
["sentence_reduced3"] = " Sekunden reduziert und du hast $",

["tooclose_lastjob"] = "Du hast bereits hier gearbeitet. Suche einen anderen Ort, um Unkraut zu jäten.",
["seizure_property"] = "Du hast dieses Grundstück beschlagnahmt! Es kann von niemandem betreten werden!",
["unseizure_property"] = "Du hast die Beschlagnahmung dieses Grundstücks aufgehoben! Jetzt kann es von jedem genutzt werden.",
["dossier_notfound"] = "The dossier dosen't exist, or you type it wrong !",
["progressbar_working"] = "Working for reducing of sentence...",
["not_anymoreon"] = "This player is not anymore online",
["dossier_desc"] = "DOSSIER: ",
}
elseif Config.Language == "FR" then
TR = {
["noinfo"] = "SUPPRIMÉ", 
["youhavejailed"] = "Vous avez été EMPRISONNÉ, votre n° de dossier est ",       
["adddossier"] = "Vous avez ajouté un DOSSIER pour ",       
["adddossier2"] = "avec NR: ",
["you_registered"] = "Vous avez inscrit un citoyen ! ",
["already_register"] = "Cette personne est déjà inscrite !",
["no_user"] = "Cette personne n’existe pas, assurez-vous que l’identifiant de la personne est valide !",
["youhavecharged"] = "Vous avez reçu une AMENDE et facturé ",
["already_released"] = "Vous avez été libéré du pénitencier, votre place n’est plus ici !",
["spawnin_jail"] = "Il semble que vous deviez finir votre sentance avant d’être libre de partir!",
["alreadyhavefood"] = "Vous avez déjà de la nourriture, mangez-la pour en avoir plus !",
["alreadyhavedrink"] = "Vous avez déjà quelques boissons, buvez-les pour en avoir plus !",
["yougetfood"] = "Vous avez de quoi manger !",
["yougetdrink"] = "Vous avez de quoi boire !",
["inv_full"] = "Vous n’avez pas d’espace pour transporter cela",
["jailed_text"] = "EMPRISONNÉ", 
["jailed_textdesc"] = "Vous êtes maintenant prisonnier du pénitencier de Sisika",  
["not_allowed"] = "Vous n’êtes pas autorisé à rester si près de cette ZONE !", 
["nomoney_bounty"] = "Vous n’avez pas assez d’argent pour ajouter cette PRIME !",
["error_insert"] = "Le montant de l’amende ou de la PRIME est incorrect, veuillez le vérifier!", 
["jailtime"] = "PEINE DE PRISON:", 
["days"] = "Jours",         
["hours"] = "Heures",  
["minutes"] = "Minutes",   
["seconds"] = "Secondes",
["m"] = "M",    
["f"] = "F",    
--MENU
["canteen"] = "Cantine",
["canteendesc"] = "Aliments pour les détenus",
["takefood"] = "Prendre la nourriture",
["takefooddesc"] = "Prenez de la nourriture",
["takedrink"] = "Prendre des boissons",
["takedrinkdesc"] = "Prenez des boissons",
["you_getregistered"] = "Vous avez été enregistré avec l'identité de",
["not_jobgrade"] = "Vous n'êtes pas autorisé à le faire",
["dossier_deleted"] = "Vous avez supprimé le DOSSIER NR:",
        
--ERRORS INPUTS
["error_description"] = "La DESCRIPTION est obligatoire !",
["error_fine"] = "L'amende est obligatoire, 0 pour PAS D'AMENDEMENT !",
["error_bounty"] = "La PRIME est requis, 0 pour PAS DE PRIME !",
["error_charge"] = "La CHARGE est OBLIGATOIRE !",
["error_jail"] = "La prison est nécessaire, 0 pour PAS DE JUSTICE !",
["error_id"] = "L'identifiant du citoyen est OBLIGATOIRE !",
["error_days"] = "Le JOUR doit être composé de 2 chiffres comme 01,05,18...",
["error_month"] = "Le MOIS doit être composé de 2 chiffres comme 01,05,12....",
["error_age"] = "L'âge doit être composé de 2 chiffres comme 21, 45, 35....",
["error_cm"] = "Le CM doit être composé de 2 chiffres comme 80,135,140....",
["error_kg"] = "Le KG doit être composé de 2 chiffres comme 55,165,35...",
["error_eyes"] = "Les YEUX doivent être composés de 2 mots comme le bleu, le noir....",
["error_hair"] = "Le mot CHEVEUX doit être composé de 2 mots comme noir, blond....",

["jail_startjob"] = "Vous avez commencé à travailler pour ce pays, vous recevrez une réduction de temps pour chaque récolte. Sortez sur le champ de la ferme pour commencer à travailler !",
["sentence_reduced1"] = "Votre peine a été réduite de ",
["sentence_reduced2"] = " secondes !",
["sentence_reduced3"] = " secondes, et a obtenu $",

["tooclose_lastjob"] = "Vous avez déjà travaillé ici, allez trouver un autre endroit pour casser les mauvaises herbes.",
["seizure_property"] = "Vous avez saisi ce bien ! Et personne ne peut y avoir accès !",
["unseizure_property"] = "Vous avez dé-saisi ce bien ! Et peut maintenant être utilisé par tout le monde", 
["dossier_notfound"] = "The dossier dosen't exist, or you type it wrong !",
["progressbar_working"] = "Working for reducing of sentence...",
["not_anymoreon"] = "This player is not anymore online",
["dossier_desc"] = "DOSSIER: ",
}
end