TR = {
        
// MAIN PAGE
DATA : "DATE: ",
MAINTITTLE : "Medic Archive's",

// SEARCH PAGE
RESULTITTLE : "Search Results",
SEARCHTITTLE : "Search Citizen",    
SFIRSTNAME : "Name: ",
SLASTNAME : "Lastname: ",    
SDOB : "DOB: ", 
SDOSSIER : "Dossier ID: ",  

// BUTTONS        
SEARCHBUTTON : "Start Search",
CLOSEBUTTON : "Close",
DELETEBUTTON : "DELETE",
ADDDOSSIER : "ADD RECORDS",
SEARCHTAB : "Search",
DOSSIERSTAB : "DOSSIERS",
        
// REGISTRY PAGE
REGISTRY : "REGISTRY",
PTITTLE1 : "MEDIC REGISTRY",
        
// RECORD DOSSIER
DOSSIER : "DOSSIER : ",
CITIZEN : "CITIZEN : ",
DOB : "DOB: ",
BOUNTY : "BOUNTY: ",
CHARGE : "CHARGE: ",
HOSPITALIZATION : "HOSPITALIZATION: ",
FINE : "FINE: ",
DATE : "REGISTERED ON: ",
DESCRIPTION : "DESCRIPTION: ",

// ADD DOSSIER
DOSSIERTITTLE : "MEDICAL RECORDS: ",
ADOSSIER : "CHARGE",
AJAIL : "HOSPITALIZATION",
AFINE : "REVIVE ONLY",
ADESCRIPTION : "Description DOSSIER: ",
    
// USER DOSSIER
UTITTLE : "IDENTITY NUMBER: ",
UNAME : "NAME: ",
UDOB : "DOB: ",
USEX : "SEX: ",
UCM : "CM: ",
UKG : "KG: ",
UEYES : "Eyes Color: ",
UHAIR : "Hair Color: ",
UFINES : "All Fines: ",
UREGISTERED : "Registered On: ",
UCITY : "CITY: ",
UDOSSIERS : "CITIZEN DOSSIERS",
}